mqcomplab/Fanpy

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

I created templates for feature requests and bug reports. These are specifically  for GitHub. It should help with keeping track of issues/new features, and who is working on them.
I used yaml files for both templates, since they can have required fields, unlike markdown templates. Currently, the template assigns a label automatically for both issues (enhancement for feature requests, and bug for bugs). The title starts either with BUG or ENH. Also, for the bug template, there is a field with package versions that is pre-populated with python, fanpy and numpy.

Create issue templates for GitHub.

---

fanpy/wfn/creation_cc.py

I updated the docstrings for CreationCC and cleaned up type hints, and unused but imported modules. The update passed the test for the CreationCC wfn.

Update docstrings in CreationCC wfn.

---

fanpy/tools/graphs.py

Update description of generate_unordered_partition in tools/graphs.py
The input list of `collection` should be ordered otherwise it results in an incorrect number of partitions and also affects the order of first elements in different bins of the same size.

Documentation correction

---

fanpy/eqn/projected.py
fanpy/interface/fanci/legacy.py
fanpy/interface/fanci/pyci.py
fanpy/interface/pyci.py

This issue arises from a current limitation in PyCI. Specifically, the Full Configuration Interaction (Full-CI) wavefunctions used in PyCI (triggered when the "fill" method is set to 'excitation') are restricted to Slater determinants with total spin projection $$S_z = 0$$.
Since the goal of this interface is to provide a seamless user experience, the initial implementation retrieves the number of projections (nproj) from Fanpy’s Objective object. However, if the user does not explicitly set the spin in the Wavefunction object, Fanpy assumes all spin cases are valid. This assumption creates a mismatch with PyCI, which only supports $$S_z = 0$$, leading to a conflict.
This issue has been addressed in [this commit]. Now, if the user specifies an nproj value larger than PyCI’s maximum …

24 bug unable to generate enough determinants for h4

---

fanpy/solver/ci.py

Solving the issue with scipy.linalg.eigh's argument 'turbo' has been removed in newer versions of scipy.
The scipy version has been tested to keep usability with older versions, but it can be removed in future updates.

Solve issue with scipy > 1.10

---

fanpy/wfn/utils.py

The (to-be) deprecated function `convert_to_fanci` was dependent on the external package FanCI (also deprecated). As a solution for this requirement, the `convert_to_fanci` imports the FanCI class from the Legacy version at the `interface` module, which is basically a copy of the old FanCI and kept available for our historical and debugging purposes.

Updating connections importing FanCI

---

tests/test_wfn_cc_standard_cc.py

The structure of `exop_combs` changed in the base CC class. The previous structure, which this test expected was:
```
exop_combs = {
(idx of anihillation and creation operators) : [[[idx excitation operator 1, idx excitation operator 2], sign],
[[idx excitation operator], sign], ...]
......
}
```
For every excitation we store the different ways we can generate it with excitation operators. In addition, we also store the sign of the excitation operator string.
In the newer structure, have a dictionary for all excitations,  where we group the excitation operator combinations based on how many excitation operators they contain. 
```
exop_combs = {
(idx of anihillation and creation operators) : { 2 : [[idx excitation operator 1, idx excitation operator 2, sign], ...],
1 : [[idx excitation …
```

Fix issue with the standard cc test

---

tests/test_wfn_cc_embedding.py

This test failed because the way we calculate the `refwfn_list` has been updated, while test remained in its original form. 
Previous `refwfn_list`:
```python
occ_indices_list = [[] for i in self.indices_list]
for i in slater.occ_indices(self.refwfn):
system_ind, j = dict_system_sub[i]
occ_indices_list[system_ind].append(j)
refwfn_list = []
for occ_indices in occ_indices_list:
refwfn_list.append(slater.create(0, *occ_indices))
self.refwfn_list = refwfn_list
```
Current `refwfn_list`:
```python
if not refwfn_list:
refwfn_list = []
for nelec, nspin in zip(nelec_list, nspin_list):
refwfn_list.append(slater.ground(nelec, nspin))
self.refwfn_list = refwfn_list
```
Both `EmbeddedCC` wavefunction tests have the same number of electrons and spinorbitals in their subsystems. Thus, they have to …

Fix the CC embedding test

---

fanpy/ham/base.py
fanpy/ham/generalized_chemical.py
fanpy/ham/restricted_chemical.py
fanpy/ham/senzero.py
fanpy/ham/unrestricted_chemical.py
fanpy/ham/utils.py
fanpy/solver/ci.py
fanpy/tools/math_tools.py
fanpy/wfn/cc/base.py
tests/test_ham_base.py
tests/test_ham_generalized_chemical.py
tests/test_ham_restricted_chemical.py
tests/test_ham_senzero.py
tests/test_ham_unrestricted_chemical.py
tests/test_solver_ci.py
tests/test_wfn_cc_base.py

This pull request aims to address the  `numpy` deprecation warnings raised when running the tests. 
In the past, `np.product` was an independent function that relied on `np.prod`. 
In more recent versions, they have become essentially the same function, and the recommendation is to use `np.prod` since `np.product` will be deprecated.
`np.math` served as a wrapper for the standard `math` module and has been replaced by `math`.
This solution is a bit more complex. The issue arises from the sign value, which can be either 1 or -1. When it is -1, redefining the NumPy array with the dtype set to `np.uint*` converts negative numbers to the maximum value available for this dtype. It was previously used to convert this number back to -1 when needed. 
Now, as this "convert" feature is no longer …

Solving Numpy depreciation warnings

---

fanpy/analysis/dataframe/base.py
fanpy/analysis/dataframe/cc.py
fanpy/analysis/dataframe/ci.py
fanpy/analysis/dataframe/geminal.py
tests/test_analysis_dataframe.py

Added missing support to MultiIndex when importing DataFrames for Geminals using CSV files.
The solution is obtained by recreating the MultiIndex system after loading.
```
self.dataframe = self.dataframe.reset_index()
self.dataframe = self.dataframe.set_index(["geminal", "pair"])
```

Improved importing CSV Dataframe for Geminals

---

fanpy/interface/fanci/pyci.py

The new `PyCI` interface calls a `mask_function` method in line 781 of `fanpy/interface/fanci/pyci.py`. This has not been declared in the scope of the class. 
**solution** 
implement the same `mask_function` as the one in the legacy interface  class (`ProjectedSchrodingerLegacyFanCI`).

fix: add mask_function to pyci interface

---

fanpy/interface/fanci/legacy.py

This pr fixes the `freeze_parameter` and `unfreeze_parameter` method in the `ProjectedSchrodingerLegacyFanCI` class, which is the legacy interface.
The code previously tried to change `self.mask` that returns the write protected `self._mask_view`. This caused: `ValueError: assignment destination is read-only`.  
**Solution:** use `self._mask` and `self._nactive`, similarly to the `(un)freeze_parameter` method in the new `ProjectedSchrodingerPyCI` class.

fix: (un)freezing parameters in legacy interface

---

fanpy/interface/fanci/legacy.py
fanpy/interface/fanci/pyci.py

There's an issue in `compute_overlap_deriv` when using `None` for chunk indices (which means a full calculation) if the number of s-space projections is less than the number of parameters.
To deal with the None values for the chunks indices, it was replaced:
```
y = np.zeros(
(f_chunk - s_chunk, self.nactive - self.mask[-1]),
dtype=pyci.c_double,
)
```
by:
```
y = np.zeros(
(len(sds), self.nactive - self.mask[-1]),
dtype=pyci.c_double,
)
```

Correcting size of overlaps deriv arrays

---

fanpy/wfn/composite/product.py
tests/test_wfn_composite_product.py

The `get_overlap` method in the `ProductWavefunction` requires `deriv` to be a list with two elements. The first is a wavefunction and the second is a 1 dimensional `numpy` array. The test expects the code to raise a `TypeError` if these requirements are not met. A previous [commit](https://github.com/mqcomplab/Fanpy/commit/fea00d32e80b322db81cae1f17c2ccc8717dce42) commented out some of the checks, which is why the test failed.
I have uncommented the checks so that the `ProductWavefunction` passes the tests.

fix: raise type error in the get overlap method of ProductWavefunction

---

tests/test_wfn_cc_standard_cc.py

The problem in #76 was the following: `scipy` had a recent release (version 1.16) that requires python 3.11 and `numpy` 1.25. One of our test cases is with python version 3.11. Thus, during the installation of `fanpy`, `numpy` was upgraded to version `2.3`. This resulted in the overflow bug in the standard CC test. Changing the `scale_sign` function fixes this issue.

test: fix sign conversion in standard cc test

---

fanpy/interface/fanci/legacy.py
fanpy/interface/fanci/pyci.py

…dSchrodingerLegacyFanCI
- Implement method to compute Hessian (second derivative) of overlap.
- Supports Fanpy get_overlap_double_derivative for each SD.
- Handles P and S spaces, converts occupations to determinants.
- Updates wavefunction parameters consistently.
- Stacks Hessian blocks into tensor for higher-order FanPT corrections.
- Mirrors compute_overlap and compute_overlap_deriv structure.

Add compute_overlap_double_deriv to ProjectedSchrodingerPyCI and ProjectedSchrodingerLegacyFanCI

---

fanpy/fanpt/containers/constant_terms.py
fanpy/fanpt/containers/energy_param.py

feat: implement 2nd and 3rd derivatives in energy_param.py for FANPT
- Added der3_g_lambda_wfnparams for ∂³G / ∂p_k ∂λ ∂p_l using V·(∂²f/∂p_k∂p_l)
- Added der3_g_wfnparams2_e for ∂³G / ∂p_k ∂p_l ∂E as -∂²f/∂p_k∂p_l
- Added der2_g_wfnparams_wfnparams
-added the additional constant terms for order 2 and 3 for higher order FANPT in constant_terms.py

feat: implemented 2nd and 3rd derivatives in energy_param.py container for FANPT and updated the constant_terms.py accordingly

---

.github/workflows/python-app.yml

This PR fixes the issue @rugwed-lokhande discovered. Previously, the test workflow would fail if the forks name is not `Fanpy`. This was because we were cloning `PyCI` in the same folder as the `Fanpy` code. We would go back to the `Fanpy` directory with `cd ../Fanpy`. 
The workflow no creates a directory called `dependencies` inside `Fanpy`. We clone and install `PyCI` in that folder. Thus, we only need to execute`cd ../../` to get back to the folder of FanPY. Below is the folder structure for the test automation: 
```bash
Fanpy_fork_name
├── dependencies
│   └── pyci
├── fanpy
├── tests
└── tools
```
We can use the `dependencies` folder if we need to install further packages manually (i.e. `git clone`).

fix: ci tests fail on forks with different name

---

fanpy/fanpt/fanpt.py

This pull request addresses the discrepancy @rugwed-lokhande and I discovered between the "old" and "new" energy free FanPT results. 
Currently, the energy is frozen both for the FanPT step and the FanCI step. However, it should only be frozen for the FanPT step. Therefore, I introduced freezing/unfreezing logic before each FanCI step that only affects energy free FanPT. Whenever the optimizer reaches a FanCI step, it checks whether the energy is supposed to be an active parameter. If it is not, it will unfreeze the energy for the FanCI calculation and freeze it afterwards. Thus, this change does not affect the eparam FanPT optimization. 
Note: we were manually freezing the energy at the end of every for loop. Thus, I only had add a "refreeze" step for the initial FanCI step before the …

fix: unfreeze energy before FanCI steps

---

fanpy/solver/wrappers.py
setup.py
tests/test_solver_wrappers.py

This pull request adds a test for the solver wrappers in the `fanpy` package, and updates the test dependencies to include `scikit-optimize`. 
**Testing improvements:**
* Added a new test file `tests/test_solver_wrappers.py` that provides tests for both `wrap_scipy` and `wrap_skopt`, covering multiple optimization methods and verifying the output structure and correctness.
* For `scipy`, it mostly tests the solvers `minimize`, `root`, and `least squares` that are the most used in the `fanpy` calculations. 
**Documentation updates:**
* Updated the docstring in `fanpy/solver/wrappers.py` for the `new_func` function to clarify that Skopt results do not include `success` or `message` attributes, and these are omitted from the output dictionary.
**Dependency updates:**
* Added …

Test: solver wrappers

---

fanpy/wfn/ci/hci.py

- Extract computation of allowed (e, s) pairs into `assign_e_s_pairs()`.
- Keep `assign_sds()` focused on enumerating Slater determinants from those pairs.
- No numerical/behavioral changes; only decomposition for readability and unit testability.
- `__init__` flow unchanged; `assign_sds()` now calls `assign_e_s_pairs()` internally.

refactor(hci): split `assign_sds` into `assign_e_s_pairs` + `assign_sds` for clarity and tests

---

tests/test_wfn_ci_hci.py

- Added test_wfn_ci_hci.py covering hCI initialization and core methods
- Verified assign_hci_pattern, assign_hci_version, assign_alphas, hierarchy
- Parametrized tests for assign_pos_hierarchies for multiple patterns
- Added reference wavefunction type/number checks
- Covered assign_sds default build, uniqueness, and error cases
- Verified calculate_e_s_pairs output for closed-shell pos_diag case
- Included smoke test for full initialization with key attributes

tests: add comprehensive unit tests for hCI wavefunction
